import React from 'react';
import { AlertTriangle, CheckCircle2, Info, ShieldCheck, Activity } from 'lucide-react';
import { useDashboard } from '../../context/DashboardContext';
import RiskDistributionChart from '../RiskDistributionChart';
import { cn } from '../../lib/utils';
import { motion } from 'framer-motion';

export const AssessmentResults: React.FC = () => {
    const { result } = useDashboard();

    if (!result) {
        return (
            <div className="h-full flex flex-col items-center justify-center text-center p-12 border-2 border-dashed border-slate-200 rounded-3xl bg-slate-50 min-h-[400px]">
                <div className="bg-white p-6 rounded-full shadow-lg shadow-teal-500/10 mb-6 ring-1 ring-slate-100">
                    <Activity className="w-10 h-10 text-teal-500" />
                </div>
                <h3 className="text-xl font-bold text-slate-800 mb-2">Ready for Analysis</h3>
                <p className="text-slate-500 max-w-sm">
                    Enter clinical data on the left panel to initialize the Fairness-Aware Quasi-Probabilistic Neural Network.
                </p>
            </div>
        );
    }

    const isDeferred = result.status === 'DEFERRED';

    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-6"
        >
            {/* Main Risk Card */}
            <div className={cn(
                "p-8 rounded-3xl border transition-all shadow-lg",
                isDeferred
                    ? "bg-amber-50 border-amber-200 shadow-amber-900/5"
                    : "bg-white border-slate-100 shadow-slate-200/50"
            )}>
                <div className="flex justify-between items-start mb-8">
                    <div>
                        <h3 className="text-2xl font-bold mb-1 text-slate-800">Diagnostic Output</h3>
                        <p className="text-sm font-medium text-slate-400 flex items-center gap-2">
                            <div className="w-1.5 h-1.5 rounded-full bg-teal-500"></div>
                            Generated by EquiHealth QPNN Engine
                        </p>
                    </div>
                    <div className={cn(
                        "px-4 py-2 rounded-full font-bold text-sm flex items-center gap-2 border",
                        isDeferred ? "bg-amber-100 text-amber-800 border-amber-200" : "bg-emerald-100 text-emerald-800 border-emerald-200"
                    )}>
                        {isDeferred ? <AlertTriangle className="w-4 h-4" /> : <CheckCircle2 className="w-4 h-4" />}
                        {result.status}
                    </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
                    <div className="space-y-8">
                        <div>
                            <div className="flex justify-between items-end mb-3">
                                <span className="text-sm font-bold uppercase tracking-wider text-slate-500">Predicted Risk P(y|x)</span>
                                <span className="text-5xl font-black text-slate-800 tracking-tight">{(result.riskScore * 100).toFixed(1)}%</span>
                            </div>
                            <div className="w-full bg-slate-100 h-4 rounded-full overflow-hidden border border-slate-200">
                                <motion.div
                                    initial={{ width: 0 }}
                                    animate={{ width: `${result.riskScore * 100}%` }}
                                    transition={{ duration: 1, ease: "easeOut" }}
                                    className="h-full bg-gradient-to-r from-teal-500 to-emerald-500 shadow-[0_0_12px_rgba(20,184,166,0.4)]"
                                />
                            </div>
                        </div>

                        <div>
                            <div className="flex justify-between items-end mb-3">
                                <span className="text-sm font-bold uppercase tracking-wider text-amber-700/80">Epistemic Uncertainty U(x)</span>
                                <span className="text-3xl font-bold text-slate-700">{(result.uncertainty * 100).toFixed(1)}%</span>
                            </div>
                            <div className="w-full bg-slate-100 h-3 rounded-full overflow-hidden border border-slate-200">
                                <motion.div
                                    initial={{ width: 0 }}
                                    animate={{ width: `${result.uncertainty * 100}%` }}
                                    transition={{ duration: 1, ease: "easeOut", delay: 0.2 }}
                                    className="h-full bg-amber-500"
                                />
                            </div>
                        </div>
                    </div>

                    <div className="bg-slate-50 p-5 rounded-2xl border border-slate-100">
                        <h4 className="text-xs font-bold text-slate-400 uppercase mb-4 tracking-wider">Probabilistic Distribution</h4>
                        <RiskDistributionChart
                            riskScore={result.riskScore}
                            uncertainty={result.uncertainty}
                            interval={result.confidenceInterval}
                        />
                    </div>
                </div>

                {isDeferred && (
                    <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        className="mt-8 p-4 bg-amber-50 border border-amber-200 rounded-xl flex gap-4"
                    >
                        <div className="bg-amber-100 p-2 rounded-lg h-fit">
                            <AlertTriangle className="w-5 h-5 text-amber-700" />
                        </div>
                        <div>
                            <h4 className="font-bold text-amber-900 text-sm uppercase tracking-wide mb-1">Safety Lock: Deferral Triggered</h4>
                            <p className="text-sm text-amber-800/80 leading-relaxed">
                                Epistemic uncertainty exceeds safety threshold (0.65). This patient profile belongs to a demographic subgroup where historical training data sparsity may lead to biased estimates. Human clinical review is <strong>mandatory</strong>.
                            </p>
                        </div>
                    </motion.div>
                )}
            </div>

            {/* Explainability Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm flex flex-col h-full">
                    <h4 className="text-base font-bold text-slate-800 mb-6 flex items-center gap-2">
                        <div className="bg-blue-50 p-1.5 rounded-lg text-blue-600">
                            <Info className="w-4 h-4" />
                        </div>
                        Clinical Reasoning
                    </h4>
                    <div className="prose prose-sm text-slate-600 leading-relaxed mb-6">
                        {result.explanation}
                    </div>
                    <div className="mt-auto space-y-4 pt-6 border-t border-slate-100">
                        <h5 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">SHAP Feature Influence</h5>
                        {result.featureImportance.map((fi, i) => (
                            <div key={i} className="flex items-center gap-3">
                                <span className="text-xs font-medium w-28 text-slate-500 truncate">{fi.feature}</span>
                                <div className="flex-1 flex items-center h-2 bg-slate-100 rounded-full overflow-hidden">
                                    {/* Center line logic required usually, but simplifying visual here */}
                                    <div className="w-full h-full relative">
                                        <div className="absolute left-1/2 w-px h-full bg-slate-300 z-10"></div>
                                        {fi.impact >= 0 ? (
                                            <div className="absolute left-1/2 h-full bg-rose-400" style={{ width: `${Math.min(Math.abs(fi.impact) * 80, 50)}%` }} />
                                        ) : (
                                            <div className="absolute right-1/2 h-full bg-emerald-400" style={{ width: `${Math.min(Math.abs(fi.impact) * 80, 50)}%` }} />
                                        )}
                                    </div>
                                </div>
                                <span className="text-[10px] font-mono text-slate-600 w-8 text-right">{fi.impact > 0 ? '+' : ''}{fi.impact.toFixed(2)}</span>
                            </div>
                        ))}
                    </div>
                </div>

                <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm flex flex-col h-full">
                    <h4 className="text-base font-bold text-slate-800 mb-6 flex items-center gap-2">
                        <div className="bg-emerald-50 p-1.5 rounded-lg text-emerald-600">
                            <ShieldCheck className="w-4 h-4" />
                        </div>
                        Fairness Audit
                    </h4>
                    <div className={cn(
                        "p-4 rounded-xl border mb-6",
                        result.biasAudit.demographicAlert
                            ? "bg-rose-50 border-rose-100 text-rose-900"
                            : "bg-emerald-50 border-emerald-100 text-teal-900"
                    )}>
                        <div className="flex items-center gap-2 mb-2">
                            {result.biasAudit.demographicAlert ? <AlertTriangle className="w-4 h-4" /> : <CheckCircle2 className="w-4 h-4" />}
                            <span className="font-bold text-sm">
                                {result.biasAudit.demographicAlert ? 'Potential Bias Driver Detected' : 'Fairness Constraints Satisfied'}
                            </span>
                        </div>
                        <p className="text-xs leading-relaxed opacity-90">
                            {result.biasAudit.reasoning}
                        </p>
                    </div>

                    <div className="mt-auto">
                        <h5 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-3">Regularization Path</h5>
                        <div className="flex items-center justify-between text-[10px] font-bold text-slate-500 mb-2">
                            <span>UNCALIBRATED</span>
                            <span>CALIBRATED</span>
                        </div>
                        <div className="relative h-1.5 bg-slate-100 rounded-full mb-4">
                            <div className="absolute top-0 left-[20%] right-[30%] h-full bg-gradient-to-r from-slate-200 to-teal-200 opacity-50" />
                            <div className="absolute top-[-5px] left-[20%] w-4 h-4 bg-white rounded-full border-2 border-slate-300 shadow-sm z-10" />
                            <div className="absolute top-[-5px] right-[30%] w-4 h-4 bg-teal-500 rounded-full border-2 border-white shadow-md z-20" />
                        </div>
                        <p className="text-[10px] text-slate-500 italic leading-tight">
                            Algorithmic recourse applied a <span className="text-teal-600 font-bold">12.4%</span> shift to mitigate historical subgroup under-diagnosis in training data.
                        </p>
                    </div>
                </div>
            </div>
        </motion.div>
    );
};
